import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  //templateUrl: './input-button-unit.component.html',
  template: `
  <p>
    input-button-unit works!
    The title is: {{ title }}
  </p>
  <p>
    <input value= "Hello World" >
    <button>Save</button>
  </p>
  <p>
    <input [value]="generateTitle()">
    <button>Save</button>
  </p>
  <p>
    <input id="my-input">
    <button>Save</button>
  </p>
  `,
  styleUrls: ['./input-button-unit.component.css']
})
export class InputButtonUnitComponent implements OnInit {
  title = "Hello World!";
  

  constructor() { 
    this.title = "I Love Angular"
    console.log(this.title);
    this.changeTitle('My First Angular App');
    console.log(this.title);
  }

  ngOnInit() {
    this.title = 'Angular CLI Rules!';
    console.log(this.title);

    setTimeout(() => {
    this.title = 'This is not the title you are looking for';
    console.log(this.title);
    }, 3000);

    let inputElement = document.getElementById('my-input');
    inputElement.value = this.title;
  }

  changeTitle(newTitle: string) {
    this.title = newTitle;
  }

  generateTitle(): string {
  return 'This title was generated by a method.';
}

}